### ISSUE TITLE
Can not seem to use Float read or write functionality

### ISSUE THREAD

**Issue by gman8a** [jmmoser/node-drivers#2]
code
--------------
const { Layers } = require('node-drivers');
const tcpLayer = new Layers.TCP({ host: '192.168.0.230', port: 44818 });
const eipLayer = new Layers.EIP(tcpLayer);
const cipPCCCLayer = new Layers.CIP.PCCC(eipLayer);
const pccc = new Layers.PCCC(cipPCCCLayer);

pccc.typedWrite('F8:1', 0, (err)=> {  if (err)console.log(err);})
pccc.typedRead( 'F8:1', (err, value)=> {
          if (err) 
                        console.log(err);
          else  console.log(value); 
        })
-------------------------------------
return this
$ node test1.js 
{ message: 'Invalid parameter or invalid data',
  info: 
   PCCCPacket {
     command: 79,
     transaction: 1,
     data: <Buffer >,
     status: 
      { code: 240,
        extended: [Object],
        description: 'Remote: Error code in the EXT STS byte' } } }
2.2779507836064226e-41

Note:
    F8:1 has a value 1.00000
    F8:2 has a value 2.00000

Any help please ?
Thanks,
Gary

------------------

**Comment by jmmoser** [comment]
@gman8a Thanks for trying out node-drivers! Can you share extended error? Console.log is abbreviating it to [Obect] in your post. Please run it again and log this: `console.log(err.info.status)`

**Comment by gman8a** [comment]
$ node test1.js 
REPLY:
code
-------------
pccc.typedWrite('F8:1', 0, (err)=> { 
                if (err) { 
                        console.log(err.info);
                        //console.log(err.info.status)
                }
})

----------------
results
-----------------
PCCCPacket {
  command: 79,
  transaction: 1,
  data: <Buffer >,
  status: 
   { code: 240,
     extended: { code: 18, description: 'Invalid parameter or invalid data' },
     description: 'Remote: Error code in the EXT STS byte' } }
2.2779507836064226e-41
^C

**Comment by gman8a** [comment]
Hi Justin,

   anything obvious?
    anything I can do to help?

Gary

**Comment by jmmoser** [comment]
@gman8a Sorry for the late response!  I just got back to the computer.  I'm going to read through the DF1 reference manual again just to make sure I'm doing this properly.  I'm also going to try reading from the PLC-5 device I have access to.

**Comment by jmmoser** [comment]
@gman8a I just tried on the device I have access to and it worked as expected.  What kind of PLC are you trying to read from? I'm wondering if your device supports the typed read command.  PLC-5, PLC-5/VME, SLC 5/03, and SLC 5/04 support typed read according to the manual.  Have you tried using `typedRead()` to read a different data type (e.g. N10:47)?

**Comment by jmmoser** [comment]
@gman8a Disregard everything I have said so far! I didn't realize it was the typedWrite that was failing, not the typedRead.  Let me dig into this again!

**Comment by gman8a** [comment]
both are failing
   the read has a goofy value
Gary

**Comment by gman8a** [comment]
Justin,


typedRead of integers works fine
typedWrite of integers also works fine;

however, both float R/W are whacked.
  let me know what i can do to help


Gary

**Comment by jmmoser** [comment]
@gman8a I think I found the issue.  I'm not encoding the type/data parameter correctly for the write request.  I'll publish an updated version to npm as soon as possible.  Thank you for pointing this out.

**Comment by gman8a** [comment]
Justin,
   excellent
     Please test Float reads too. I think they be bd; when i write a value
using another LLD/ driver, and read back with yours, get wacky value.
Gary

**Comment by gman8a** [comment]
Also do you have a feel for re-connection ability of your driver
 if i unplug the cable, the highest layer does not see and connect errors;
    so can not rip down the conn. and start over with anew.

Gary

**Comment by jmmoser** [comment]
@gman8a I know I’ve read floats before and received values I expected but I’ll take another look at that section of the code.  Without writing any values, what value do you receive when you read F8:1 with node-drivers and what value do you receive when you read F8:1 with the other driver?

All layers in node-drivers (_should_) handle connecting and reconnecting for you. However, since you asked I just realized the TCP layer does not handle reconnecting currently.  This will be very simple to add.

**Comment by gman8a** [comment]
// Other driver
~/wic/ccs$ ./rw_plc5 read_F 8 1
F8:1=1.000003


// WRITE
=======================
~/wic/ccs$ node test1.js
PCCCPacket {
  command: 79,
  transaction: 1,
  data: <Buffer >,
  status:
   { code: 240,
     extended: { code: 18, description: 'Invalid parameter or invalid data'
},
     description: 'Remote: Error code in the EXT STS byte' } }
^C

READ
================
~/wic/ccs$ node test1.js
-190570791299973120

**Comment by jmmoser** [comment]
@gman8a I just published a new pre-release to npm that includes updates to the PCCC type/data parameter encoding.  You can upgrade to this release with `npm i --save node-drivers@beta`.  Please let me know if this fixes the issue!

**Comment by gman8a** [comment]
Hi Justin,
  Got this error :

$ node test1.js

/mnt/WIC/node_modules/node-drivers/src/layers/tcp/TCPLayer.js:31
  static async* Scan(hosts, ports) {
             ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous>
(/mnt/WIC/node_modules/node-drivers/src/index.js:5:10)

**Comment by jmmoser** [comment]
@gman8a What version of node are you using?

**Comment by gman8a** [comment]
/ccs$ node -v
v8.10.0

**Comment by jmmoser** [comment]
@gman8a Are you upgrade to upgrade to v12 or v13?

**Comment by gman8a** [comment]
I did, that solved the "generator" function issue,
   however now
        1) the typedWrite does not work for either N7 and F8
        2) typedRead works for N7 but not F8

NOTE: Below I the integer read is correct value because I stuffed ndx slot
using another LLD.  The node-driver write are broke.

=========== code ============
// https://github.com/jmmoser/node-drivers

const { Layers } = require('node-drivers');
const tcpLayer = new Layers.TCP({ host: '192.168.0.230', port: 44818 });
const eipLayer = new Layers.EIP(tcpLayer);
const cipPCCCLayer = new Layers.CIP.PCCC(eipLayer);
const pccc = new Layers.PCCC(cipPCCCLayer);

//-----------------------
// FLOAT test
pccc.typedWrite('F8:1', 0, (err)=> {
if (err) {
console.log(err.info);
  //console.log(err.info.status)
}
})

setTimeout( ()=>{
pccc.typedRead('F8:1', (err, value)=> {
 if (err)
console.log(err);
 else console.log('F8:1 = ',value);
})
}, 2000);



//-----------------------
// INT test
var ndx=44

if(1)
pccc.typedWrite(`N7:${ndx}`, ndx, (err)=> {
if (err) {
console.log(err.info);
  //console.log(err.info.status)
}
})


setTimeout( ()=>{
pccc.typedRead(`N7:${ndx}`, (err, value)=> {
 if (err)
console.log(err);
 else console.log(`N7:${ndx} = `,value);
})
}, 2000);


//end-of-file



============= OUTPUT ==============
vOne:~/wic/ccs$ node test3.js
PCCCPacket {
  command: 79,
  transaction: 1,
  data: <Buffer >,
  status: {
    code: 240,
    extended: { code: 18, description: 'Invalid parameter or invalid data'
},
    description: 'Remote: Error code in the EXT STS byte'
  },
  raw: <Buffer 4f f0 01 00 12>
}
PCCCPacket {
  command: 79,
  transaction: 2,
  data: <Buffer >,
  status: {
    code: 240,
    extended: { code: 18, description: 'Invalid parameter or invalid data'
},
    description: 'Remote: Error code in the EXT STS byte'
  },
  raw: <Buffer 4f f0 02 00 12>
}
F8:1 =  2.134995919469862e-39
N7:44 =  44
^C^C

**Comment by gman8a** [comment]
Justin,
  Hurray you fixed it.
     Both read and write of floats and integer now work !!!!


      + node-drivers@2.0.0-beta.3

===========
/ccs$ node test3.js
N7:47 47
F8:1 =  3.299999952316284
N7:47 =  47
^C
============
ccs$ node test3.js
N7:47 47
F8:1 =  12345
N7:47 =  47
^C

**Comment by jmmoser** [comment]
@gman8a Awesome!  After receiving your response yesterday I realized I still wasn't encoding the data/type parameter correctly for typedWrite.  I was hopeful that typedRead would start returning values you expect after typedWrite starts working.  Thank you for your patience and persevering through this with me!  I really appreciate your help!

**Comment by gman8a** [comment]
Justin,
   I did an analysis of the float data return from node driver.
   You are converting the 4 bytes incorrectly, however they are read
corrected

   this is what i did.
         1) write float value with other LLD
         2) read float with node-driver with debug output.
         3) debug the buffer


===========================
SrvOne:~/wic/sandbox$ cat d1.txt

**** added debug to file
   vim ~/node_modules/node-drivers/src/layers/pccc/PCCCLayer.js

 typedRead(address, items, callback) {
if (callback == null && typeof items === 'function') {
 callback = items;
 items = undefined;
}

return Layer.CallbackPromise(callback, resolver => {
 const itemsSpecified = items != null;

 if (itemsSpecified) {
if ((!Number.isFinite(items) || items <= 0 || items > 0xFFFF)) {
 return resolver.reject('If specified, items must be a positive integer
between 1 and 65535');
}
 } else {
items = 1;
 }

 const transaction = incrementTransaction(this);
 const message = PCCCPacket.TypedReadRequest(transaction, address, items);

 this.send(message, null, false, this.contextCallback(function (error,
reply) {
if (error) {
 resolver.reject(error, reply);
} else {

console.log(reply)//%GLA

 const value = PCCCPacket.ParseTypedReadData(reply.data);
 if (items === 1 && Array.isArray(value) && value.length > 0) {
resolver.resolve(value[0]);
 } else {
resolver.resolve(value);
 }
}
 }, transaction));
});
 }


////////// TEST 1 ////////////////

**** Other LLD write float value 1.0
SrvOne:~/wic/sandbox$ ./rw_plc5 write_F 8 0 1.0
SrvOne:~/wic/sandbox$ node test3
PCCCPacket {
  command: 79,
  transaction: 1,
  data: <Buffer 99 09 06 94 08 80 3f 00 00>,
                               xx            2nd    byte order

                                  xx         1st
                                     xx      4th
                                        xx   3rd

      using: https://babbage.cs.qc.cuny.edu/IEEE-754.old/32bit.html
Hexadecimal Representation: 3F800000   ------> YILEDS d'1.0

  status: { code: 0, extended: { code: 0 }, description: 'Success' },
  raw: <Buffer 4f 00 01 00 99 09 06 94 08 80 3f 00 00>
}

F8:0 =  2.2779507836064226e-41    <----- NODE-DRIVER WRONG INTERPRETATION
OF BUFFER


////////// TEST 2 ////////////////

SrvOne:~/wic/sandbox$ ./rw_plc5 write_F 8 0 2.0
SrvOne:~/wic/sandbox$ node test3
PCCCPacket {
  command: 79,
  transaction: 1,
  data: <Buffer 99 09 06 94 08 00 40 00 00>,
  status: { code: 0, extended: { code: 0 }, description: 'Success' },
  raw: <Buffer 4f 00 01 00 99 09 06 94 08 00 40 00 00>
}

F8:0 =  2.2958874039497803e-41  <----- NODE-DRIVER WRONG INTERPRETATION OF
BUFFER


////////////// test 3 ///////////////////////////

rSrvOne:~/wic/sandbox$ ./rw_plc5 write_F 8 0 3021.333
SrvOne:~/wic/sandbox$ ./rw_plc5 read_F 8 0
F8:0=3021.333008

SrvOne:~/wic/sandbox$ node test3
PCCCPacket {
  command: 79,
  transaction: 1,
  data: <Buffer 99 09 06 94 08 3c 45 54 d5>,
                               xx            2nd    byte order

                                  xx         1st
                                     xx      4th
                                        xx   3rd

      using: https://babbage.cs.qc.cuny.edu/IEEE-754.old/32bit.html
Hexadecimal Representation: 453cd554   ------> YILEDS d'3021.3330

  status: { code: 0, extended: { code: 0 }, description: 'Success' },
  raw: <Buffer 4f 00 01 00 99 09 06 94 08 3c 45 54 d5>
}
F8:0 =  -14587114029056

**Comment by gman8a** [comment]
Justin,
   This shows both the correct and incorrect order to process the buffer
    My CPU is ARM 7

    PS, your buffer stuffing for float writes may also need same attention.

    Maybe your driver is working on AMD/Intel CPUs because the byte order
may be correct.

Gary



////////// TEST 2 ////////////////

SrvOne:~/wic/sandbox$ ./rw_plc5 write_F 8 0 2.0
SrvOne:~/wic/sandbox$ node test3
PCCCPacket {
  command: 79,
  transaction: 1,
  data: <Buffer 99 09 06 94 08 00 40 00 00>,
  status: { code: 0, extended: { code: 0 }, description: 'Success' },
  raw: <Buffer 4f 00 01 00 99 09 06 94 08 00 40 00 00>
 node-driver-wrongly    correct order using ARM CPU
                                          xx               4th
      2nd
                                             xx            3rd
      1st
                                                xx         2nd
      4th
                                                   xx      1st
      3rd
}

F8:0 =  2.2958874039497803e-41  <----- NODE-DRIVER WRONG INTERPRETATION OF
BUFFER

**Comment by gman8a** [comment]
Justin,

  I modified file:
     ~/node_modules/node-drivers/src/layers/pccc/PCCCPacket.js

==================

function __TypedReadReplyParser(data, offset, info) {
  let value;

  switch (info.typeID) {
    case PCCCDataType.Binary:
    case PCCCDataType.BitString:
    case PCCCDataType.Byte:
      value = data.readUInt8(offset);
      break;
    case PCCCDataType.Integer:
      value = data.readUInt16LE(offset);
      break;

    case PCCCDataType.Float:

                if(true){
                        //console.log(data)//%GLA
                        //console.log(info) //%GLA

                        let buf= new Buffer(4);
                        // swap some bytes around
                        if(false){
                                //using BigEndian
                                buf[0]=data[offset+1]
                                buf[1]=data[offset+0]
                                buf[2]=data[offset+3]
                                buf[3]=data[offset+2]
                                value = buf.readFloatBE(0);
                        }
                        else{
                                //using LittleEndian
                                buf[0]=data[offset+2]
                                buf[1]=data[offset+3]
                                buf[2]=data[offset+0]
                                buf[3]=data[offset+1]
                                value = buf.readFloatLE(0);
                        }
                }
                else{
                        value = data.readFloatLE(offset);
                }
      break;

**Comment by jmmoser** [comment]
@gman8a node-drivers reads and writes floats with little-endian byte ordering because my copy of Allen-Bradley's DF1 Protocol and Command Set Reference Manual specifies on page 13-17 the lowest byte is first (little-endian) for typed reads.  I write floats with little-endian byte ordering simply because I read them little-endian.  I also compared the float values read by node-drivers with a commercial application and the values are the exact same.  Do you have the source code for the other "LLD" you are using (rw_plc5)?

Regarding your latest post, I was actually planning on updating wordRangeRead() to do something very similar to your code!

**Comment by gman8a** [comment]
Justin,

SrvOne:~/wic/sandbox$ cat rw_plc5
#! /bin/bash
#
# by Gary Argraves
# Purpose Read and write tags to PLC5
# Oct. 25, 2019
# uses libplctag  see  https://github.com/kyle-github/libplctag
#   see BUILD.md for instruction for CMAKE and make
#

#program that reads and writes to PLC5
plc_ip="192.168.0.230"
prog="${HOME}/libplctag/build/bin_dist/tag_rw"
tagPath="protocol=ab_eip&gateway=${plc_ip}&cpu=PLC5&debug=0"

#----------------------------------------
# @brief
# read N? array
#
function read_N(){
  local file=$1
  local ndx=$2 # start reading at N#:ndx
  local cnt=$3 # number of elements

  ${prog} -t sint16 -p
"${tagPath}&elem_size=2&elem_count=${cnt}&name=N${file}:${ndx}"|
     awk -vndx="${ndx}" -vfile="${file}"  '

/data/{
  split($1,a,"=")
  print "N" file ":" ndx++ "=" a[2]
}'
} #fn

#----------------------------------------
# @brief
# read F? array
#
function read_F(){
  local file=$1
  local ndx=$2 # start reading at F#:ndx
  local cnt=$3 # number of elements

  ${prog} -t real32 -p
"${tagPath}&elem_size=4&elem_count=${cnt}&name=F${file}:${ndx}"|
     awk -vndx="${ndx}" -vfile="${file}"  '

/data/{
  split($1,a,"=")
  print "F" file ":" ndx++ "=" a[2]
}'
} #fn

#----------------------------------------
# @brief
# read F? array
#
function read_F_one(){
  local file=$1
  local ndx=$2 # start reading at F#:ndx
  local cnt="1" # number of elements

  ${prog} -t real32 -p
"${tagPath}&elem_size=4&elem_count=${cnt}&name=F${file}:${ndx}"
} #fn


#----------------------------------------
# @brief
#       write single value to N? array
#
function write_N(){
  local file=$1
  local ndx=$2
  local val=$3

  ${prog} -t sint16 -p
"${tagPath}&elem_size=2&elem_count=1&name=N${file}:${ndx}" -w ${val} >
/dev/null
} #fn

#----------------------------------------
# @brief
#       write single value to F? array
#
function write_F(){
  local file=$1
  local ndx=$2
  local val=$3

  ${prog} -t real32 -p
"${tagPath}&elem_size=4&elem_count=1&name=F${file}:${ndx}" -w ${val} >
/dev/null
} #fn


# -------- Main line ------------
#echo $1 $2 $3 $4
plc_fn=$1
file=$2
ndx=$3
cnt=$4 # is also write value
${plc_fn} $file $ndx $cnt

# end of file

**Comment by gman8a** [comment]
Justin,
  I modified the write portion of your code:

==================================
function typedWriteEncodeValue(buffer, offset, type, value) {

  switch (type) {
    case PCCCDataType.Binary:
    case PCCCDataType.Byte:
      return buffer.writeUInt8(value, offset);
    case 'INT':
    case PCCCDataType.Integer:
      return buffer.writeUInt16LE(value, offset);
    case 'DINT':
      return buffer.writeUInt32LE(value, offset);


    case 'REAL':
    case PCCCDataType.Float:

          if(true){  //%GLA

                        console.log(buffer, offset, type, value) //%GLA
                    let buflen= buffer.writeFloatLE(value, offset);
                        console.log(buflen, buffer)

                        // swap some bytes around
                        let offset2=buflen-4
                        //using LittleEndian

                        let b0=buffer[offset2+0]
                        let b1=buffer[offset2+1]
                        let b2=buffer[offset2+2]
                        let b3=buffer[offset2+3]

                        buffer[offset2+0]=b2
                        buffer[offset2+1]=b3
                        buffer[offset2+2]=b0
                        buffer[offset2+3]=b1

                        console.log(buflen, buffer)
                        return buflen
                }
                else{
                     return buffer.writeFloatLE(value, offset);
                }

    default:
      throw new Error(`Unable to encode value of type: ${type}`);
  }
}

============== OUTPUT ================

SrvOne:~/wic/sandbox$ vim test3.js
SrvOne:~/wic/sandbox$ node test3
<Buffer 67 00 00 01 00 00 24 46 38 3a 30 00 94 08 00 00 98 03> 14 REAL
13021.333
18 <Buffer 67 00 00 01 00 00 24 46 38 3a 30 00 94 08 55 75 4b 46>
18 <Buffer 67 00 00 01 00 00 24 46 38 3a 30 00 94 08 4b 46 55 75>
N7:47 12047
F8:0 =  13021.3330078125
N7:47 =  12047
^C

SrvOne:~/wic/sandbox$ ./rw_plc5 read_F 8 0
F8:0=13021.333008

**Comment by gman8a** [comment]
Justin,
  FYI

   I have been assuming the byte order implemented (*other LLD libplctag*
 see  https://github.com/kyle-github/libplctag)  is correct
   Maybe your byte order is correct.
   I can not tell which is correct.
   I do know that when using 2 byte integers the order seems to match as I
can write using one then read using other and it is correct (and
visa-a-versa)

  Gary

**Comment by jmmoser** [comment]
@gman8a I think this is an issue with the discrepancies of the word ordering between a PCCC typed read, a PCCC word range read, a PCCC typed write, and a PCCC word range write for floats.

Page 13-17 of Allen-Bradley's DF1 Protocol and Command Set Reference Manual shows the bytes received from a typed read of the value 1000.0 are [0x00, 0x00, 0x7A, 0x44] and the bytes received from a word range read of the value 1000.0 are [0x7A, 0x44, 0x00, 0x00].   The byte order for the typed read is IEEE floating point with little-endian byte ordering.  The byte order for the word range read is the same as the typed read except it is high word first then low word.

Pages 10 through 11 of this [document](https://www.kepware.com/getattachment/92260762-d789-4699-b52a-e96b42f158ba/allen-bradley-df1-manual.pdf) state the word ordering for a float transmitted from a PLC-5 device is high word first then low word although it does not state if this is from a typed read request or a word range read request.  I tested node-drivers and `typedRead()` of a float address returned low word then high word and `wordRangeRead()` of the same float address returned high word then low word.

In your bash script your tagPath specifies `cpu=PLC5`. In libplctag's source code this maps the tag's vtable to `plc5_vtable` which uses [word range read](https://github.com/kyle-github/libplctag/blob/b56f4e9bff0aae7f6f4460b7083f060472002965/src/protocols/ab/eip_plc5_pccc.c#L221) for reading the tag and [word range write](https://github.com/kyle-github/libplctag/blob/b56f4e9bff0aae7f6f4460b7083f060472002965/src/protocols/ab/eip_plc5_pccc.c#L512) for writing to the tag.

In your tests you have been using your bash script to write the float value and node-drivers to read the float value.  I am curious to know what would happen if you used node-drivers to write the value (using `typedWrite()`) and then used your bash script to read the value.  My guess is your bash script will not return the value you expect.

I am also curious to know what would happen if you updated the tagPath in your bash script to `cpu=lgxpccc`, tried writing to the tag using your bash script, then read the value with node-drivers.  My guess is node-drivers will return the value you expect.

**Comment by jmmoser** [comment]
@gman8a I am actually most curious to know what happens if you do this:

1. Set `cpu=PLC5` in the tagPath of your bash script
2. Write a value using your bash script (_./rw_plc5 write_F 8 0 1.0_)
3. Set `cpu=lgxpccc` in the tagPath of your bash script
4. Read the value using your bash script (_./rw_plc5 read_F 8 0_)

I would do it myself but I don't have a PLC5 device that I am comfortable writing to.  Let me know what the results are if you can!

**Comment by gman8a** [comment]
Justin,
   I changed the CPU type and tried many combinations of R/W.  The LLD does
not return data using cpu=LGX or cpu=lgxpccc.

   Tomorrow I will confirm byte order using A/B logix5000 s/w.

   The byte order swapping that works now is coded :

========================
function typedWriteEncodeValue(buffer, offset, type, value) {

  switch (type) {
    case PCCCDataType.Binary:
    case PCCCDataType.Byte:
      return buffer.writeUInt8(value, offset);
    case 'INT':
    case PCCCDataType.Integer:
      return buffer.writeUInt16LE(value, offset);
    case 'DINT':
      return buffer.writeUInt32LE(value, offset);

    case 'REAL':
    case PCCCDataType.Float:

          if(true){  //%GLA

                        //console.log(buffer, offset, type, value) //%GLA

                    let buflen= buffer.writeFloatLE(value, offset);
                        //console.log(buflen, buffer) // before byte swap

                        // swap some bytes around
                        let offset2=buflen-4
                        //using LittleEndian

                        let b0=buffer[offset2+0]
                        let b1=buffer[offset2+1]
                        let b2=buffer[offset2+2]
                        let b3=buffer[offset2+3]

                        buffer[offset2+0]=b2
                        buffer[offset2+1]=b3
                        buffer[offset2+2]=b0
                        buffer[offset2+3]=b1

                        //console.log(buflen, buffer) // after byte swap
                        return buflen
                }
                else{
                     return buffer.writeFloatLE(value, offset);
                }

    default:
      throw new Error(`Unable to encode value of type: ${type}`);
  }
}

=========================================

function __TypedReadReplyParser(data, offset, info) {
  let value;

  switch (info.typeID) {
    case PCCCDataType.Binary:
    case PCCCDataType.BitString:
    case PCCCDataType.Byte:
      value = data.readUInt8(offset);
      break;
    case PCCCDataType.Integer:
      value = data.readUInt16LE(offset);
      break;

    case PCCCDataType.Float:
                if(true){
                        //console.log(data)//%GLA
                        //console.log(info) //%GLA

                        // fastest
                         let buf = Buffer.from([ data[offset+2],
                                                 data[offset+3],
                                                 data[offset+0],
                                                 data[offset+1] ])
                    value = buf.readFloatLE(0);
                }
                else{
                   value = data.readFloatLE(offset);
                }
      break;


Gary

**Comment by gman8a** [comment]
Justin,

   I tested node-driver r/w of the PLC 5 against the A/B Logix5000 program
which I assume is gold standard for proper r/w action.

   The result is that YOUR ORIGINAL code is CORRECT. It reads and writes
floats properly, thus your byte order is correct.

   This also means that the "other" LLD that I have been using with
cpu=PLC5  IS WRONG.

Gary

**Comment by jmmoser** [comment]
@gman8a Hurray!  Thank you for confirming!  I will keep this in mind when I redesign the PCCC layer in the future to include PLC-specific layers.
