### ISSUE TITLE
Cannot run examples on README.md

### ISSUE THREAD

**Issue by DAZ-NZ-Eng** [jmmoser/node-drivers#8]
Hi, 
I've tried running the example below after installing node-drivers:
"Read/Write a tag from a PLC-5, SLC 5/03, or SLC 5/04 processor using PCCC embedded in CIP:"
However, I keep getting the following error:

console.log(await pccc.typedWrite('N10:47', 1000));
            ^^^^^

SyntaxError: missing ) after argument list
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47

anyone have come across this issue?

**Comment by jmmoser** [comment]
@DAZ-NZ-Eng Can you share more of your code? You have an imbalance of parentheses according to the error.

**Comment by DAZ-NZ-Eng** [comment]
Hi @jmmoser here is the code:

const { TCP, CIP, PCCC } = require('node-drivers');

const tcpLayer = new TCP('172.17.217.243');
const cipLayer = new CIP(tcpLayer);
const pccc = new PCCC(cipLayer);

/** Write an integer */
console.log(await pccc.typedWrite('N10:47', 1000));

/** Read an integer */
console.log(await pccc.typedRead('N7:0'));

/** Write a float */
console.log(await pccc.typedWrite('F8:1', 5.5));

tcpLayer.close();

**Comment by jmmoser** [comment]
Try this:

```javascript
const { TCP, CIP, PCCC } = require('node-drivers');

const tcpLayer = new TCP('172.17.217.243');
const cipLayer = new CIP(tcpLayer);
const pccc = new PCCC(cipLayer);

(async () => {
	  /** Write an integer */
	  console.log(await pccc.typedWrite('N10:47', 1000));
	  
	  /** Read an integer */
	  console.log(await pccc.typedRead('N7:0'));
	  
	  /** Write a float */
	  console.log(await pccc.typedWrite('F8:1', 5.5));
	  
	  await tcpLayer.close();
})();
```
I have it written the other way in the README just to keep the snippets as bare-bones as possible but the function calls with `await` need to be called inside of an async function.

**Comment by DAZ-NZ-Eng** [comment]
Hi @jmmoser 
Thanks for your quick solution. I've ran this and it appears to be working correctly now. Much appreciated.
